### ISSUE TITLE
the format for idat files

### ISSUE THREAD

**Issue by hmyh1202** [Christensen-Lab-Dartmouth/Normal-breast-5hmC#3]
Hello:

How prepare the array data of idat format? 

The data pairs as below when download and decompression it into a folder:
GSM1905306_3999941120_R03C01_Grn.idat
GSM1905306_3999941120_R03C01_Red.idat

I have download all array files into a folder without rename that files and prepared a meta file which looks like:
 ID      OX_BS   Sample_Sex      Sample_Age      Sample_Well     Beadchip        Position
B10A    0       F       77.6    -       3999941120      R03C01
B10B    1       F       77.6    -       3999941120      R05C01
B11A    0       F       45.3    -       3999941120      R03C02
B11B    1       F       45.3    -       3999941120      R02C02
... ...

If it right for you scripts ?

The Best !

**Comment by owenwilkins** [comment]
Hi there, 

You should be able to read data into these scripts following the standard minfi protocol for reading in IDATs. Assuming you are using a more recent version of minfi than when this script was written, you will need to use the read.metharray() function rather than read.450k(), which is now deprecated in minfi. 

Hope that is helpful.

**Comment by hmyh1202** [comment]
yes, thank you
